variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=/opt/cache/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

image: maven:3.3.9-jdk-8

build:
  stage: build
  script: mvn $MAVEN_OPTS clean compile

verify:
  stage: test
  script:
    - 'mvn $MAVEN_OPTS verify'
